//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploNexus.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Payrolls = new HashSet<Payroll>();
        }
    
        public int emp_ID { get; set; }
        public string emp_Name { get; set; }
        public string emp_Gender { get; set; }
        public string emp_Email { get; set; }
        public string emp_Department { get; set; }
        public string emp_Position { get; set; }
        public Nullable<decimal> emp_Salary { get; set; }
        public Nullable<int> emp_UserID { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
        public virtual ICollection<Payroll> Payrolls { get; set; }
    }
}
