//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploNexus.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int emp_No { get; set; }
        public int emp_ID { get; set; }
        public string emp_name { get; set; }
        public int emp_genderId { get; set; }
        public System.DateTime emp_DOB { get; set; }
        public string emp_email { get; set; }
        public int emp_departmentId { get; set; }
        public int emp_positionId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Position Position { get; set; }
    }
}
