//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploNexus.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        public int payroll_ID { get; set; }
        public System.DateTime payroll_PayDate { get; set; }
        public decimal payroll_Amount { get; set; }
        public Nullable<int> payroll_EmployeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
