//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploNexus.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int salary_ID { get; set; }
        public decimal salary_Amount { get; set; }
        public System.DateTime salary_PayDate { get; set; }
        public int Salaryemp_ID { get; set; }
    }
}
