//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploNexus.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_all_employee
    {
        public int EMPLOYEE_NO_ { get; set; }
        public int EMPLOYEE_ID { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public int GENDER { get; set; }
        public System.DateTime BIRTHDATE { get; set; }
        public string EMAIL { get; set; }
        public int DEPARTMENT { get; set; }
        public int JOB_POSITION { get; set; }
    }
}
