//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploNexus.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_emp_Attendance
    {
        public int EMPLOYEE_ID { get; set; }
        public System.DateTime DATE { get; set; }
        public int STATUS { get; set; }
    }
}
